const express = require('express');
const cors = require("cors");
const accountSID ="AC56fc5b37803205fe2b7aa4cd3b04d967";
const accountToken ="37fc05b0e6d65f10bd311812541c9293";
const client = require('twilio')(accountSID,accountToken);

const app = express();

app.use(cors());




app.get('/send-text', (req, res) => {
  const {recipient} = req.query; // retrives the recipient POST from the header request page!

  client.messages
  .create({
     body: "Thank you for subscribing to our news feed!",   //Text message body, put anything here to send to people 
     from: '+18592956473', // DO NOT CHANGE THIS, this is the PH number that was generated by twilio
     to: "+61"+recipient // recipient phone number. Only works for aus sorry!
   }).then((message) => console.log(message.body))
  

})

app.listen(4000, () => console.log("Running on Port 4000")); // port opened on 4000 might need to be changed later on